### ISSUE TITLE
.technical_indicator() ignores options.

### ISSUE THREAD

**Issue by fluffyx** [Finnhub-Stock-API/finnhub-ruby#4]
This is from the examples, but changing the timeperiod (or using another option in Finnhub's docs) does not change the output.

```
puts(finnhub_client.technical_indicator("AAPL", 'D', 1583098857, 1584308457, 'rsi', {"timeperiod": 3}))
```

**Comment by fluffyx** [comment]
What does work is the following, but it seems it could be refactored to give it more ease of use.

```
finnhub_client.technical_indicator("AAPL", 'D', 1583098857, 1584308457, 'ema', {**query_params**:{'timeperiod': 3}})
```

**Comment by finnhubio** [comment]
Hi there,

I can confirm this is correct. We will update the docs asap. You can either use query_params or indicator_fields to specify the indicator parameters.

`puts(finnhub_client.technical_indicator("AAPL", 'D', 1583098857, 1584308457, 'rsi', {indicator_fields:{'timeperiod': 3}}))
`
